//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5_thfm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Log
    {
        public int id_event { get; set; }
        public string @event { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
