//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5_thfm2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillType> BillTypes { get; set; }
        public virtual DbSet<ClassroomDay1> ClassroomDay1 { get; set; }
        public virtual DbSet<ClassroomDay2> ClassroomDay2 { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Event_Log> Event_Log { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<StatusPay> StatusPays { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
