//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5_thfm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Register()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int Register_Id { get; set; }
        public string Titlename { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<int> ClassroomDay1_Id { get; set; }
        public Nullable<int> ClassroomDay2_Id { get; set; }
        public Nullable<int> StatusPay_Id { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateChk { get; set; }
        public Nullable<int> Login_Id { get; set; }
        public string User_Edit { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public byte[] img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ClassroomDay1 ClassroomDay1 { get; set; }
        public virtual ClassroomDay2 ClassroomDay2 { get; set; }
        public virtual Login Login { get; set; }
        public virtual StatusPay StatusPay { get; set; }
    }
}
