//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5_thfm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Register_Id { get; set; }
        public string Titlename { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ClassroomDay1_Name { get; set; }
        public string ClassroomDay2_Name { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public string CompanyType_Name { get; set; }
        public string CompanyName { get; set; }
        public string Contact_Firstname { get; set; }
        public string Contact_Lastname { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Tex { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Price { get; set; }
        public string Address_1 { get; set; }
        public string Township_1 { get; set; }
        public string Amphoe_1 { get; set; }
        public string Province_1 { get; set; }
        public string ZipCode_1 { get; set; }
        public string AddressSend { get; set; }
        public string TownshipSend { get; set; }
        public string AmphoeSend { get; set; }
        public string ProvinceSend { get; set; }
        public string ZipCodeSend { get; set; }
        public string BillType_Name { get; set; }
        public string l_Firstname { get; set; }
        public string l_Lastname { get; set; }
        public string l_Email { get; set; }
        public string StatusPay_Name { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        public string Contact_Email { get; set; }
    }
}
